export const QUANTITY_UP_START = 'QUANTITY_UP_START';
export const QUANTITY_UP_SUCCESS = 'QUANTITY_UP_SUCCESS';
export const QUANTITY_DOWN_START = 'QUANTITY_DOWN_START';
export const QUANTITY_DOWN_SUCCESS = 'QUANTITY_DOWN_SUCCESS';

export const QUANTITY_UP = 'QUANTITY_UP';
export const QUANTITY_DOWN = 'QUANTITY_DOWN';
export const QUANTITY_ASYNC_UP = 'QUANTITY_ASYNC_UP';
export const QUANTITY_ASYNC_DOWN = 'QUANTITY_ASYNC_DOWN';
